# Generated by Django 5.1.4 on 2025-01-22 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='related_tasks_field',
        ),
        migrations.AlterField(
            model_name='project',
            name='tasks',
            field=models.ManyToManyField(blank=True, null=True, related_name='projects', to='management.task'),
        ),
    ]
