# Generated by Django 5.1.4 on 2025-01-22 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_remove_project_related_tasks_field_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='tasks',
        ),
    ]
