# Generated by Django 5.1.4 on 2025-05-07 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_customuser_must_change_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Government', 'Government'), ('Company_Head', 'Company_Head'), ('Company_Employee', 'Company_Employee'), ('Public', 'Public')], default='Public', max_length=50),
        ),
    ]
